security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    role_hierarchy:
        ROLE_CA: ROLE_CC
        ROLE_AS: ROLE_CA
        ROLE_ADMIN: ROLE_AS
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
            main:
                    pattern: ^/
                    anonymous: true
                    provider: fos_userbundle
                    form_login:
                         login_path: fos_user_security_login
                         check_path: fos_user_security_check
                    logout:
                        path: fos_user_security_logout
                        target: /
            dev:
               pattern:  ^/(_(profiler|wdt)|css|images|js)/
               security: false
    access_control:

        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_CC }
        - { path: /admin, roles: ROLE_ADMIN }