<?php

namespace TRC\CoreBundle\Repository;

/**
 * StatutAlerteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutAlerteRepository extends \Doctrine\ORM\EntityRepository
{
}
