services:



#*********** LES SYSTEMES ******************

    trc_core.central:
        class: TRC\CoreBundle\Systemes\Central\Central
        arguments: []
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager","@trc_core.gu"]]
    trc_core.export:
        class: TRC\CoreBundle\Systemes\Data\Export

    trc_core.sp:
        class: TRC\CoreBundle\Systemes\SP\Pagination
        arguments: []
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
    
    trc_core.matricule:
        class: TRC\CoreBundle\Systemes\Matricule\Matricule
        arguments: []
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    trc_core.journal:
        class: TRC\CoreBundle\Systemes\Journal\Journal
        arguments: []
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
    trc_core.noti:
        class: TRC\CoreBundle\Systemes\Journal\Noti
        arguments: []
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager","@trc_core.gu"]]
    trc_core.twig.extension:
        class: TRC\CoreBundle\Systemes\Twig\TwigExtension
        arguments: ["@doctrine.orm.entity_manager","@trc_core.gu","@trc_core.ddc"]
        tags:
            - { name: twig.extension }

    trc_core.gu:
        class: TRC\CoreBundle\Systemes\General\GU
        arguments: []
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
    trc_core.sgf:
        class: TRC\CoreBundle\Systemes\General\SGF
        arguments: []
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
    trc_core.ddc:
        class: TRC\CoreBundle\Systemes\General\DDC
        arguments: ["@trc_core.gu"]
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
    trc_core.pagination:
        class: TRC\CoreBundle\Systemes\Pagination\Pagination
        arguments: []
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]